services:
  arangodb:
    container_name: "parteincerta-arangodb-${TAG}"
    image: "${IMAGE}:${TAG}"
    init: true
    # mdkir /tmp/.arangodb && cat /dev/urandom | head -c 32 > /tmp/.arangodb/ek
    # command: "arangod --encryption.keyfile /tmp/.arangodb/ek"
    ports:
      - 8529:8529
    volumes:
      - arangodb:/var/lib/arangodb3
      - arangodb-apps:/var/lib/arangodb3-apps
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
    network_mode: bridge

volumes:
  arangodb:
    name: parteincerta-arangodb
  arangodb-apps:
    name: parteincerta-arangodb-apps
