services:
  nginx:
    container_name: "parteincerta-nginx-${TAG}"
    image: "${IMAGE}:${TAG}-${TAG_EXTRA}"
    init: true
    ports:
      - 8081:8081
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./conf.d/:/etc/nginx/conf.d/:ro"
      - nginx-log:/var/log
      - nginx-tmpfs:/var/cache/nginx
      - nginx-tmpfs:/var/run
    network_mode: bridge

volumes:
  nginx-log:
    name: parteincerta-nginx-log
  nginx-tmpfs:
    name: parteincerta-nginx-tmpfs
    driver_opts:
      type: tmpfs
      device: tmpfs
