services:
  minio:
    container_name: "parteincerta-minio-${TAG}"
    image: "${IMAGE}:${TAG}-${TAG_EXTRA}"
    init: true
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_KMS_AUTO_ENCRYPTION=${MINIO_KMS_AUTO_ENCRYPTION}
      - MINIO_KMS_SECRET_KEY=${MINIO_KMS_SECRET_KEY}
    network_mode: bridge

volumes:
  minio:
    name: parteincerta-minio
